import type React from 'react';
import { font, color, surface, edge, radius, primitives } from '../../../shared/theme';

// 메탈릭 다크 + 아니메풍 + 절제된 네온 (PRODUCT.md). 토큰은 게임 공유 theme.ts.
const neon = color.neon;
const neonGlow = color.neonGlow;
const metalCard = surface.card;
const metalCardFocused = surface.cardFocused;
const metalPanel = surface.panel;
const metalEdge = edge.metal;

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    background: surface.screen,
    color: color.ink,
    fontFamily: font.body,
    position: 'relative',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 24px',
    background: surface.panel,
    borderBottom: `1px solid ${color.line}`,
    boxShadow: '0 1px 0 rgba(255, 255, 255, 0.04), 0 6px 16px -10px rgba(0, 0, 0, 0.8)',
  },
  title: {
    ...primitives.title,
  },
  titleAccent: primitives.titleAccent,
  addSongBtn: {
    ...primitives.neonButton,
    minHeight: 'auto',
    padding: '7px 16px',
    fontSize: '13px',
  },
  tutorialHelpBtn: {
    width: '34px',
    height: '34px',
    padding: 0,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: surface.button,
    color: '#f0f0f0',
    border: `1px solid ${color.line}`,
    borderRadius: radius.pill,
    boxShadow: edge.metal,
    cursor: 'pointer',
    fontFamily: font.display,
    fontSize: '16px',
    fontWeight: 800,
    lineHeight: 1,
    flexShrink: 0,
  },
  refreshBtn: {
    ...primitives.metalButton,
    minHeight: 'auto',
    padding: '7px 16px',
    fontSize: '13px',
  },
  settingsBtn: {
    ...primitives.metalButton,
    minHeight: 'auto',
    padding: '7px 16px',
    fontSize: '13px',
  },
  backBtn: {
    ...primitives.ghostButton,
    minHeight: 'auto',
    padding: '7px 16px',
    fontSize: '13px',
  },
  splitContainer: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  leftPanel: {
    width: '45%',
    maxWidth: '480px',
    minWidth: '320px',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '20px',
    borderRight: `1px solid ${color.line}`,
    overflowY: 'auto',
  },
  jacketContainer: {
    width: '100%',
    aspectRatio: '1',
    background: 'linear-gradient(145deg, #1a1d22, #0e1013)',
    border: `1px solid ${color.line}`,
    borderRadius: radius.md,
    overflow: 'hidden',
    boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.05)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  jacketImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  detailInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  detailTitle: {
    fontFamily: font.display,
    fontSize: '18px',
    fontWeight: 700,
    letterSpacing: '0.005em',
    lineHeight: '1.3',
    color: '#f1f4f7',
  },
  detailArtist: {
    fontSize: '13px',
    color: color.inkDim,
  },
  detailDuration: {
    fontFamily: font.numeric,
    fontSize: '13px',
    color: color.inkFaint,
  },
  detailChartTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  detailActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginTop: 'auto',
    paddingTop: '12px',
  },
  songList: {
    flex: 1,
    overflow: 'auto',
    paddingTop: 'calc(50vh - 60px)',
    paddingBottom: 'calc(50vh - 60px)',
    paddingLeft: '24px',
    paddingRight: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    scrollbarWidth: 'none',
  },
  songListState: {
    paddingTop: '20px',
    paddingBottom: '20px',
    justifyContent: 'center',
  },
  empty: {
    textAlign: 'center',
    color: color.inkDim,
    fontSize: '14px',
    padding: '24px',
  },
  songCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    background: surface.card,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: color.line,
    borderRadius: radius.md,
    boxShadow: edge.metal,
    cursor: 'pointer',
    transition: 'border-color 80ms, box-shadow 80ms, opacity 80ms ease, transform 80ms ease, background 80ms',
    transformOrigin: 'center',
  },
  songCardFocused: {
    borderColor: color.neon,
    background: surface.cardFocused,
    boxShadow: `inset 0 0 0 1px ${color.neon}, ${edge.metal}, 0 0 20px -6px ${color.neonGlow}`,
  },
  songInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    minWidth: 0,
    flex: 1,
  },
  songTitle: {
    fontFamily: font.display,
    fontSize: '15px',
    fontWeight: 700,
    color: '#f1f4f7',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  songArtist: {
    fontSize: '13px',
    color: color.inkDim,
  },
  songDuration: {
    color: color.inkFaint,
  },
  chartTags: {
    display: 'flex',
    gap: '6px',
    flexShrink: 0,
    marginLeft: '16px',
    alignItems: 'center',
  },
  chartTag: {
    padding: '4px 11px',
    color: '#fff',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#555',
    borderRadius: radius.pill,
    boxShadow: edge.metal,
    cursor: 'pointer',
    fontFamily: font.numeric,
    fontSize: '12px',
    fontWeight: 700,
    letterSpacing: '0.03em',
    transition: 'box-shadow 0.15s',
    userSelect: 'none',
  },
  chartTagFocused: {
    borderColor: color.neon,
    boxShadow: `inset 0 0 0 1px ${color.neon}, ${edge.metal}, 0 0 12px -3px ${color.neonGlow}`,
  },
  playBtn: {
    padding: '10px 28px',
    background: 'linear-gradient(180deg, #27b552, #178a3c)',
    color: '#fff',
    border: '1px solid #34d067',
    borderRadius: radius.sm,
    boxShadow: `${edge.metal}, 0 0 16px -8px rgba(52, 208, 103, 0.6)`,
    cursor: 'pointer',
    fontFamily: font.display,
    fontSize: '15px',
    fontWeight: 700,
    letterSpacing: '0.03em',
  },
  bottomEditBtn: {
    ...primitives.neonButton,
    minHeight: 'auto',
    padding: '9px 20px',
  },
  bottomNewChartBtn: {
    padding: '9px 16px',
    background: 'transparent',
    color: color.inkDim,
    border: `1px dashed ${color.line}`,
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontFamily: font.display,
    fontSize: '13px',
    fontWeight: 600,
  },
  bottomDeleteBtn: {
    padding: '9px 16px',
    background: 'transparent',
    color: color.danger,
    border: `1px solid ${color.danger}55`,
    borderRadius: radius.sm,
    cursor: 'pointer',
    fontFamily: font.display,
    fontSize: '13px',
    fontWeight: 600,
  },
  mobileContainer: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    height: '100dvh',
    // 평면 회색 대신 상단에서 은은히 밝아지는 다크 메탈 배경
    background: 'radial-gradient(120% 80% at 50% -10%, #171b21 0%, #0d0f12 55%)',
    color: '#e8ecf0',
    fontFamily: font.body,
    position: 'relative',
    overflow: 'hidden',
  },
  mobileHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '14px 14px 12px',
    background: metalPanel,
    borderBottom: '1px solid #2a2f38',
    boxShadow: '0 1px 0 rgba(255, 255, 255, 0.04), 0 6px 16px -10px rgba(0, 0, 0, 0.8)',
    flexShrink: 0,
  },
  mobileHeaderTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  mobileTitle: {
    margin: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontFamily: font.display,
    fontSize: '22px',
    lineHeight: 1,
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#f4f7fa',
  },
  // 제목 앞 얇은 네온 틱 (아니메풍 액센트 — 카드 사이드보더 아님)
  mobileTitleAccent: {
    width: '4px',
    height: '22px',
    borderRadius: '2px',
    background: `linear-gradient(180deg, ${neon}, #2b8f93)`,
    boxShadow: `0 0 10px -1px ${neonGlow}`,
    flexShrink: 0,
  },
  mobileEmail: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: '#8a919b',
    fontSize: '12px',
  },
  mobileHeaderActions: {
    display: 'flex',
    gap: '8px',
    overflowX: 'auto',
    paddingBottom: '2px',
    scrollbarWidth: 'none',
  },
  mobileActionButton: {
    minHeight: '44px',
    padding: '0 15px',
    background: 'linear-gradient(180deg, #2a2f37 0%, #1e2229 100%)',
    color: '#d7dde4',
    // border 단축 대신 롱핸드 — mobilePrimaryActionButton이 borderColor만 덮어써도 안전
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#363c46',
    borderRadius: '9px',
    boxShadow: metalEdge,
    cursor: 'pointer',
    fontFamily: font.display,
    fontSize: '14px',
    fontWeight: 600,
    letterSpacing: '0.01em',
    whiteSpace: 'nowrap',
    touchAction: 'manipulation',
  },
  mobilePrimaryActionButton: {
    // 관리자 주액션 — 유일하게 네온 엣지를 두른 버튼
    background: 'linear-gradient(180deg, #16333a 0%, #102429 100%)',
    borderColor: '#3f8f94',
    color: '#d8fbfd',
    boxShadow: `${metalEdge}, 0 0 12px -6px ${neonGlow}`,
  },
  mobileTutorialHelpBtn: {
    width: '44px',
    minWidth: '44px',
    padding: 0,
    borderRadius: '999px',
    fontSize: '18px',
    fontWeight: 800,
  },
  mobileSongList: {
    flex: 1,
    overflowY: 'auto',
    padding: '14px 12px calc(88px + env(safe-area-inset-bottom))',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    WebkitOverflowScrolling: 'touch',
    overscrollBehavior: 'contain',
    scrollPaddingBottom: '88px',
  },
  mobileSongListState: {
    paddingTop: '20px',
    paddingBottom: 'calc(20px + env(safe-area-inset-bottom))',
    justifyContent: 'center',
  },
  mobileSongCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '14px',
    background: metalCard,
    // border 단축 대신 롱핸드 — 포커스 시 borderColor만 토글해도 React 경고가 없다
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#2b303a',
    borderRadius: '12px',
    boxShadow: metalEdge,
    cursor: 'pointer',
    touchAction: 'manipulation',
    transition: 'border-color 140ms ease, box-shadow 140ms ease, transform 140ms ease',
  },
  mobileSongCardFocused: {
    // 포커스된 카드에만 네온 — 얇은 엣지 + 절제된 글로우
    background: metalCardFocused,
    borderColor: neon,
    boxShadow: `${metalEdge}, 0 0 0 1px ${neon}, 0 0 20px -6px ${neonGlow}`,
  },
  mobileSongHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '14px',
    minWidth: 0,
  },
  mobileJacket: {
    width: 'clamp(96px, 28vw, 124px)',
    aspectRatio: '1',
    flexShrink: 0,
    background: 'linear-gradient(145deg, #1a1d22, #0e1013)',
    border: '1px solid #2b303a',
    borderRadius: '10px',
    overflow: 'hidden',
    boxShadow: 'inset 0 1px 0 rgba(255, 255, 255, 0.05)',
  },
  mobileJacketImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  mobileSongInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    minWidth: 0,
    paddingTop: '2px',
  },
  mobileSongTitle: {
    fontFamily: font.display,
    fontSize: '17px',
    lineHeight: 1.25,
    fontWeight: 700,
    letterSpacing: '0.005em',
    color: '#f1f4f7',
    overflowWrap: 'anywhere',
  },
  mobileSongArtist: {
    fontSize: '13px',
    lineHeight: 1.35,
    color: '#9aa2ac',
  },
  mobileChartRows: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    overflowX: 'auto',
    scrollbarWidth: 'none',
    WebkitOverflowScrolling: 'touch',
    // overflowX:auto → overflowY도 auto로 계산돼 세로/가로 모두 클리핑된다.
    // 포커스 글로우가 잘리지 않게 사방 여백을 준다.
    padding: '4px 4px',
  },
  mobileChartTag: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '38px',
    padding: '0 14px',
    color: '#fff',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#555',
    borderRadius: '9px',
    boxShadow: metalEdge,
    cursor: 'pointer',
    fontFamily: font.numeric,
    fontSize: '13px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    whiteSpace: 'nowrap',
    userSelect: 'none',
    touchAction: 'manipulation',
    transition: 'box-shadow 140ms ease, transform 140ms ease',
  },
  mobileChartTagFocused: {
    // 아웃셋 링은 스크롤 컨테이너에 잘리므로 보더+inset으로 크리스프 네온 엣지를
    // 버튼 안쪽에 그린다(절대 안 잘림). 바깥 글로우만 부드럽게 얹는다.
    borderColor: neon,
    boxShadow: `inset 0 0 0 1px ${neon}, ${metalEdge}, 0 0 12px -3px ${neonGlow}`,
  },
  mobileEditBtn: {
    width: '100%',
    minHeight: '44px',
    padding: '0 14px',
    background: 'linear-gradient(180deg, #16333a 0%, #102429 100%)',
    color: '#d8fbfd',
    border: `1px solid ${neon}`,
    borderRadius: '9px',
    boxShadow: `${metalEdge}, 0 0 14px -7px ${neonGlow}`,
    cursor: 'pointer',
    fontFamily: font.display,
    fontSize: '14px',
    fontWeight: 700,
    letterSpacing: '0.02em',
    touchAction: 'manipulation',
  },
  mobileEditBtnDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
  },
  mobileNewChartBtn: {
    minHeight: '44px',
    padding: '0 14px',
    backgroundColor: 'transparent',
    color: '#aab1bb',
    border: '1px dashed #4a505b',
    borderRadius: '9px',
    cursor: 'pointer',
    fontFamily: font.display,
    fontSize: '14px',
    fontWeight: 600,
    touchAction: 'manipulation',
  },
};
