import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    backgroundColor: '#1a1a1a',
    color: '#e0e0e0',
    fontFamily: 'system-ui, sans-serif',
    position: 'relative',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px 24px',
    backgroundColor: '#2a2a2a',
    borderBottom: '1px solid #333',
  },
  title: {
    margin: 0,
    fontSize: '20px',
    fontWeight: 600,
  },
  addSongBtn: {
    padding: '6px 16px',
    backgroundColor: '#4488ff',
    color: '#fff',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
  },
  refreshBtn: {
    padding: '6px 16px',
    backgroundColor: '#3a3a3a',
    color: '#e0e0e0',
    border: '1px solid #555',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '13px',
  },
  settingsBtn: {
    padding: '6px 16px',
    backgroundColor: '#3a3a3a',
    color: '#e0e0e0',
    border: '1px solid #555',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '13px',
  },
  backBtn: {
    padding: '6px 16px',
    backgroundColor: 'transparent',
    color: '#888',
    border: '1px solid #444',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '13px',
  },
  splitContainer: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  leftPanel: {
    width: '45%',
    maxWidth: '480px',
    minWidth: '320px',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '20px',
    borderRight: '1px solid #333',
    overflowY: 'auto',
  },
  jacketContainer: {
    width: '100%',
    aspectRatio: '1',
    backgroundColor: '#111',
    borderRadius: '8px',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  jacketImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  detailInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  detailTitle: {
    fontSize: '17px',
    fontWeight: 700,
    lineHeight: '1.3',
  },
  detailArtist: {
    fontSize: '13px',
    color: '#999',
  },
  detailDuration: {
    fontSize: '12px',
    color: '#666',
  },
  detailChartTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  detailActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginTop: 'auto',
    paddingTop: '12px',
  },
  songList: {
    flex: 1,
    overflow: 'auto',
    paddingTop: 'calc(50vh - 60px)',
    paddingBottom: 'calc(50vh - 60px)',
    paddingLeft: '24px',
    paddingRight: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    scrollbarWidth: 'none',
  },
  songListState: {
    paddingTop: '20px',
    paddingBottom: '20px',
    justifyContent: 'center',
  },
  empty: {
    textAlign: 'center',
    color: '#888',
    fontSize: '14px',
    padding: '24px',
  },
  songCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 16px',
    backgroundColor: '#2a2a2a',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#333',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'border-color 80ms, box-shadow 80ms, opacity 80ms ease, transform 80ms ease, background-color 80ms',
    transformOrigin: 'center',
  },
  songCardFocused: {
    borderColor: '#00ffff',
    boxShadow: '0 0 8px 2px #00ffff44',
    backgroundColor: '#303030',
  },
  songInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    minWidth: 0,
    flex: 1,
  },
  songTitle: {
    fontSize: '15px',
    fontWeight: 600,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  songArtist: {
    fontSize: '13px',
    color: '#999',
  },
  songDuration: {
    color: '#666',
  },
  chartTags: {
    display: 'flex',
    gap: '6px',
    flexShrink: 0,
    marginLeft: '16px',
    alignItems: 'center',
  },
  chartTag: {
    padding: '3px 10px',
    color: '#fff',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#555',
    borderRadius: '12px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 500,
    transition: 'box-shadow 0.15s',
    userSelect: 'none',
  },
  chartTagFocused: {
    boxShadow: '0 0 0 2px #00ffff',
  },
  playBtn: {
    padding: '8px 28px',
    backgroundColor: '#22aa44',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: 600,
  },
  bottomEditBtn: {
    padding: '8px 20px',
    backgroundColor: 'transparent',
    color: '#4488ff',
    border: '1px solid #4488ff66',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 500,
  },
  bottomNewChartBtn: {
    padding: '8px 16px',
    backgroundColor: 'transparent',
    color: '#888',
    border: '1px dashed #555',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
  },
  bottomDeleteBtn: {
    padding: '8px 16px',
    backgroundColor: 'transparent',
    color: '#cc4444',
    border: '1px solid #cc444466',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 500,
  },
  mobileContainer: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    height: '100dvh',
    backgroundColor: '#181818',
    color: '#e8e8e8',
    fontFamily: 'system-ui, sans-serif',
    position: 'relative',
    overflow: 'hidden',
  },
  mobileHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    padding: '12px',
    backgroundColor: '#242424',
    borderBottom: '1px solid #383838',
    flexShrink: 0,
  },
  mobileHeaderTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  mobileTitle: {
    margin: 0,
    fontSize: '20px',
    lineHeight: 1.2,
    fontWeight: 700,
  },
  mobileEmail: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: '#9a9a9a',
    fontSize: '12px',
  },
  mobileHeaderActions: {
    display: 'flex',
    gap: '8px',
    overflowX: 'auto',
    paddingBottom: '2px',
    scrollbarWidth: 'none',
  },
  mobileActionButton: {
    minHeight: '44px',
    padding: '0 14px',
    backgroundColor: '#343434',
    color: '#ededed',
    border: '1px solid #505050',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    whiteSpace: 'nowrap',
    touchAction: 'manipulation',
  },
  mobilePrimaryActionButton: {
    backgroundColor: '#2f67d8',
    borderColor: '#4b7df0',
    color: '#fff',
  },
  mobileSongList: {
    flex: 1,
    overflowY: 'auto',
    padding: '12px 12px calc(88px + env(safe-area-inset-bottom))',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    WebkitOverflowScrolling: 'touch',
    overscrollBehavior: 'contain',
    scrollPaddingBottom: '88px',
  },
  mobileSongListState: {
    paddingTop: '20px',
    paddingBottom: 'calc(20px + env(safe-area-inset-bottom))',
    justifyContent: 'center',
  },
  mobileSongCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    padding: '14px',
    backgroundColor: '#262626',
    border: '1px solid #3a3a3a',
    borderRadius: '8px',
    cursor: 'pointer',
    touchAction: 'manipulation',
  },
  mobileSongCardFocused: {
    borderColor: '#75d9dc',
    backgroundColor: '#2c3030',
  },
  mobileSongHeader: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '14px',
    minWidth: 0,
  },
  mobileJacket: {
    width: 'clamp(96px, 28vw, 124px)',
    aspectRatio: '1',
    flexShrink: 0,
    backgroundColor: '#151515',
    border: '1px solid #3a3a3a',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  mobileJacketImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  mobileSongInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
    minWidth: 0,
    paddingTop: '2px',
  },
  mobileSongTitle: {
    fontSize: '16px',
    lineHeight: 1.3,
    fontWeight: 700,
    overflowWrap: 'anywhere',
  },
  mobileSongArtist: {
    fontSize: '13px',
    lineHeight: 1.35,
    color: '#ababab',
  },
  mobileChartRows: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    overflowX: 'auto',
    scrollbarWidth: 'none',
    WebkitOverflowScrolling: 'touch',
    paddingBottom: '2px',
  },
  mobileChartTag: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '36px',
    padding: '0 12px',
    color: '#fff',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#555',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '11px',
    fontWeight: 700,
    whiteSpace: 'nowrap',
    userSelect: 'none',
    touchAction: 'manipulation',
  },
  mobileChartTagFocused: {
    boxShadow: '0 0 0 2px #75d9dc',
  },
  mobileEditBtn: {
    width: '100%',
    minHeight: '44px',
    padding: '0 14px',
    backgroundColor: '#1f385f',
    color: '#dbe9ff',
    border: '1px solid #4b74b8',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 700,
    touchAction: 'manipulation',
  },
  mobileEditBtnDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
  },
  mobileNewChartBtn: {
    minHeight: '44px',
    padding: '0 14px',
    backgroundColor: 'transparent',
    color: '#b8b8b8',
    border: '1px dashed #686868',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    touchAction: 'manipulation',
  },
  toastContainer: {
    position: 'fixed',
    bottom: '80px',
    right: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    zIndex: 3000,
    pointerEvents: 'none',
  },
  toast: {
    padding: '8px 16px',
    backgroundColor: 'rgba(180, 80, 0, 0.9)',
    color: '#fff',
    borderRadius: '6px',
    fontSize: '13px',
    whiteSpace: 'nowrap',
    boxShadow: '0 2px 8px rgba(0,0,0,0.4)',
  },
};
